apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  namespace: ${{ values.namespace }}
  labels: {app: ${{ values.name }}}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector: {app: ${{ values.name }}}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
