apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
  name: prod-web-deny-all
  namespace: ingress-gateway
spec:
  rules:
    authorization:
      deny-all:
        metrics: false
        opa:
          allValues: false
          rego: allow = true
        priority: 0
    response:
      unauthorized:
        body:
          value: |
            {
              "error": "Forbidden",
              "message": "Access denied by default by the gateway operator. If you are the administrator of the service, create a specific auth policy for the route."
            }
        headers:
          content-type:
            value: application/json
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: prod-web
