apiVersion: v1
imagePullSecrets:
  - name: discount-access-sa-dockercfg-txm4f
kind: ServiceAccount
metadata:
  annotations:
    openshift.io/internal-registry-pull-secret-ref: discount-access-sa-dockercfg-txm4f
  name: discount-access-sa
  namespace: travel-agency
secrets:
  - name: discount-access-sa-dockercfg-txm4f
