apiVersion: v1
kind: Service
metadata:
  labels:
    app: insurances
  name: insurances
  namespace: travel-agency
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: insurances
  sessionAffinity: None
  type: ClusterIP
