apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: echo-api
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: echo-api
    helm.sh/chart: echo-api-0.1.0
  name: echo-api
  namespace: echo-api
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: echo-api
    app.kubernetes.io/name: echo-api
  sessionAffinity: None
  type: ClusterIP
